name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        path: go/src/platypus/

    - name: Build
      #go build .
      run: go build -o platypus.exe
      env:
        GOPATH: /home/runner/work/platypus/go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: platypus
        path: /home/runner/work/platypus/go/src/platypus/platypus.exe
        
    - name: Test
      run: go test ./board
    
    - name: Benchmark
      run: go test -bench=. ./board
