name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: go/src/

    - name: Build
      #go build .
      run: |
        pwd
        echo ${GOPATH}
        go build .
      env:
        GOPATH: /home/runner/work/go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: platypus
        path: platypus.exe
        
    - name: Test
      run: go test ./board
    
    - name: Benchmark
      run: go test -bench=. ./board
